### ISSUE TITLE
add an application_name option in profile for postgres connection

### ISSUE THREAD

**Issue by nworr** [jelix/JelixDatabase#2]
profile file could accept the [application_name connection parameter](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-APPLICATION-NAME) for postgreSQL connection

and maybe always use the _fallback_application_name_ with a genreric value ?

**Comment by laurentj** [comment]
Profiles for postgresql accepts the `pg_options` parameters, which can be used to set `application_name`, as indicated [in this comment](https://www.php.net/manual/fr/function.pg-connect.php#119642).

**Comment by nworr** [comment]
live tested : i add
`pg_options="--application_name=MyApp"
`
on my profile, it works as expected 👍
